# Generated by Django 2.0.2 on 2018-02-27 19:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('updated', models.DateTimeField()),
                ('body', models.TextField()),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'simple_articles',
                'ordering': ('-updated',),
            },
        ),
    ]
